CREATE DATABASE IF NOT EXISTS `RECETTES` DEFAULT CHARACTER SET UTF8MB4 COLLATE utf8_general_ci;
USE `RECETTES`;

CREATE TABLE `CATÉGORIE` (
  `nom` VARCHAR(42),
  `` VARCHAR(42),
  PRIMARY KEY (`nom`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `COMMENTAIRE` (
  `content` VARCHAR(42),
  `` VARCHAR(42),
  `titre` VARCHAR(42),
  `nom` VARCHAR(42),
  PRIMARY KEY (`content`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `CONTIENT` (
  `nom` VARCHAR(42),
  `titre` VARCHAR(42),
  PRIMARY KEY (`nom`, `titre`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `CONTIENT2` (
  `numéro` VARCHAR(42),
  `titre` VARCHAR(42),
  PRIMARY KEY (`numéro`, `titre`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `ETAPE` (
  `numéro` VARCHAR(42),
  `description` VARCHAR(42),
  `` VARCHAR(42),
  PRIMARY KEY (`numéro`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `INGRÉDIENT` (
  `nom` VARCHAR(42),
  `quantité` VARCHAR(42),
  `unité` VARCHAR(42),
  `` VARCHAR(42),
  PRIMARY KEY (`nom`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `MESSAGE` (
  `nom` VARCHAR(42),
  `contenue` VARCHAR(42),
  `mail` VARCHAR(42),
  `` VARCHAR(42),
  PRIMARY KEY (`nom`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `POSSÈDE` (
  `nom` VARCHAR(42),
  `titre` VARCHAR(42),
  PRIMARY KEY (`nom`, `titre`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `RECETTE` (
  `titre` VARCHAR(42),
  `durée` VARCHAR(42),
  `nomimage` VARCHAR(42),
  `rating` VARCHAR(42),
  `` VARCHAR(42),
  `nom` VARCHAR(42),
  `nom_1` VARCHAR(42),
  PRIMARY KEY (`titre`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `SAISON` (
  `nom` VARCHAR(42),
  `` VARCHAR(42),
  PRIMARY KEY (`nom`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `USER` (
  `nom` VARCHAR(42),
  `mail` VARCHAR(42),
  `avatar` VARCHAR(42),
  `password` VARCHAR(42),
  `role` VARCHAR(42),
  `` VARCHAR(42),
  PRIMARY KEY (`nom`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

ALTER TABLE `COMMENTAIRE` ADD FOREIGN KEY (`nom`) REFERENCES `USER` (`nom`);
ALTER TABLE `COMMENTAIRE` ADD FOREIGN KEY (`titre`) REFERENCES `RECETTE` (`titre`);
ALTER TABLE `CONTIENT` ADD FOREIGN KEY (`titre`) REFERENCES `RECETTE` (`titre`);
ALTER TABLE `CONTIENT` ADD FOREIGN KEY (`nom`) REFERENCES `INGRÉDIENT` (`nom`);
ALTER TABLE `CONTIENT2` ADD FOREIGN KEY (`titre`) REFERENCES `RECETTE` (`titre`);
ALTER TABLE `CONTIENT2` ADD FOREIGN KEY (`numéro`) REFERENCES `ETAPE` (`numéro`);
ALTER TABLE `POSSÈDE` ADD FOREIGN KEY (`titre`) REFERENCES `RECETTE` (`titre`);
ALTER TABLE `POSSÈDE` ADD FOREIGN KEY (`nom`) REFERENCES `USER` (`nom`);
ALTER TABLE `RECETTE` ADD FOREIGN KEY (`nom_1`) REFERENCES `CATÉGORIE` (`nom`);
ALTER TABLE `RECETTE` ADD FOREIGN KEY (`nom`) REFERENCES `SAISON` (`nom`);